#define yy_create_buffer BAS_create_buffer
#define yy_delete_buffer BAS_delete_buffer
#define yy_scan_buffer BAS_scan_buffer
#define yy_scan_string BAS_scan_string
#define yy_scan_bytes BAS_scan_bytes
#define yy_flex_debug BAS_flex_debug
#define yy_init_buffer BAS_init_buffer
#define yy_flush_buffer BAS_flush_buffer
#define yy_load_buffer_state BAS_load_buffer_state
#define yy_switch_to_buffer BAS_switch_to_buffer
#define yyin BASin
#define yyleng BASleng
#define yylex BASlex
#define yyout BASout
#define yyrestart BASrestart
#define yytext BAStext
#define yywrap BASwrap

#line 20 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\\\BASscan.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/tse/tse/engine/console/BASscan.cpp,v 1.4 2006/09/13 23:32:26 bramage Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


 /* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
//nclude <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

 /* Enter a start condition.  This macro really ought to take a parameter,
  * but we do it the disgusting crufty way forced on us by the ()-less
  * definition of BEGIN.
  */
#define BEGIN yy_start = 1 + 2 *

  /* Translate the current start state into a value that can be later handed
   * to BEGIN to return to the state.  The YYSTATE alias is for lex
   * compatibility.
   */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

   /* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state* YY_BUFFER_STATE;

extern int yyleng;
extern FILE* yyin, * yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

 /* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
{
    FILE* yy_input_file;

    char* yy_ch_buf;		/* input buffer */
    char* yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


 /* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = (char*)0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO((FILE* input_file));

void yy_switch_to_buffer YY_PROTO((YY_BUFFER_STATE new_buffer));
void yy_load_buffer_state YY_PROTO((void));
YY_BUFFER_STATE yy_create_buffer YY_PROTO((FILE* file, int size));
void yy_delete_buffer YY_PROTO((YY_BUFFER_STATE b));
void yy_init_buffer YY_PROTO((YY_BUFFER_STATE b, FILE* file));
void yy_flush_buffer YY_PROTO((YY_BUFFER_STATE b));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO((char* base, yy_size_t size));
YY_BUFFER_STATE yy_scan_string YY_PROTO((yyconst char* str));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO((yyconst char* bytes, int len));

static void* yy_flex_alloc YY_PROTO((yy_size_t));
static void* yy_flex_realloc YY_PROTO((void*, yy_size_t));
static void yy_flex_free YY_PROTO((void*));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE* yyin = (FILE*)0, * yyout = (FILE*)0;
typedef int yy_state_type;
extern char* yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO((void));
static yy_state_type yy_try_NUL_trans YY_PROTO((yy_state_type current_state));
static int yy_get_next_buffer YY_PROTO((void));
static void yy_fatal_error YY_PROTO((yyconst char msg[]));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[205] =
{ 0,
    0,    0,   93,   91,    1,    5,    4,   48,   91,   91,
   55,   54,   91,   38,   39,   42,   40,   53,   41,   47,
   43,   88,   88,   49,   50,   44,   58,   45,   35,   34,
   86,   86,   86,   86,   36,   37,   56,   86,   86,   86,
   86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
   51,   46,   52,   57,    1,    0,    9,    0,    6,    0,
    0,   17,   85,   25,   12,   26,    0,    7,    0,   23,
   16,   21,   15,   22,    2,   24,    0,   88,    0,    0,
   14,   19,   11,    8,   10,   20,   86,   31,   86,   86,
   27,   86,   86,   86,   86,   86,   86,   86,   66,   86,

   86,   86,   86,   86,   64,   86,   59,   86,   86,   86,
   86,   86,   86,   71,   86,   86,   28,   13,   18,   90,
   85,    0,    2,   89,    0,   89,   87,   29,   30,   33,
   32,   86,   86,   86,   86,   86,   86,   86,   86,   68,
   86,   69,   86,   76,   86,   86,   86,   86,   75,   86,
   86,   86,   86,   90,    0,   86,   86,   78,   70,   86,
   86,   86,   62,   86,   86,   86,    3,   86,   72,   86,
   65,   83,   86,   67,   60,   86,   86,   86,   84,   86,
   86,    3,    3,   86,   86,   63,   86,   86,   86,   86,
   86,   61,   80,   86,   86,   81,   86,   82,   79,   73,

   86,   74,   77,    0
};

static yyconst int yy_ec[256] =
{ 0,
    1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
    2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
   12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
   20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
   24,   25,   26,   27,   28,   29,   30,   31,   32,   31,
   33,   33,   33,   33,   33,   34,   33,   35,   33,   36,
   33,   33,   37,   38,   33,   33,   33,   39,   33,   33,
   40,   41,   42,   43,   33,    1,   44,   45,   46,   47,

   48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
   57,   58,   33,   59,   60,   61,   62,   33,   63,   39,
   33,   33,   64,   65,   66,   67,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1
};

static yyconst int yy_meta[68] =
{ 0,
    1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
    4,    1,    1,    5,    1,    1,    1,    3,    3,    3,
    3,    3,    6,    6,    6,    6,    6,    6,    6,    1,
    1,    1,    1,    3,    3,    3,    3,    3,    3,    6,
    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
    6,    6,    6,    1,    1,    1,    1
};

static yyconst short int yy_base[215] =
{ 0,
    0,    0,  281,  282,  278,  282,  282,   61,   63,   51,
   53,   65,   66,  282,  282,  255,   64,  282,   63,  282,
   62,   64,   73,  257,  282,   71,  253,   73,  282,  282,
    0,  242,  239,  246,  282,  282,  249,   43,   57,   65,
   54,   67,  223,  223,  211,  225,  220,   54,   68,  216,
  282,   58,  282,  282,  264,  241,  282,   93,  282,  260,
  111,  282,  242,  282,  282,  282,  108,  282,  258,  282,
  282,  282,  282,  282,    0,  282,  113,  118,  125,    0,
  282,  237,  282,  282,  282,  236,    0,    0,  229,  229,
  282,  207,  208,  195,  197,  197,  191,  202,    0,  190,

  202,  194,  188,  190,    0,  182,    0,  198,   65,  195,
  197,  189,  192,    0,  177,  186,  282,  282,  282,  216,
  215,  214,    0,  123,  127,  132,    0,  282,  282,    0,
    0,  182,  189,  184,  172,  169,  185,  184,  179,    0,
  166,    0,  179,    0,  171,  221,  160,  163,    0,  159,
  163,  170,  163,  195,  190,  152,  148,    0,    0,  146,
  149,  131,    0,  142,  128,  139,  177,  114,    0,  124,
    0,    0,  121,    0,    0,  112,  113,  111,    0,  112,
  113,    0,  160,  105,  109,    0,   97,  101,   96,   99,
  106,    0,  146,  100,   94,    0,   80,    0,  282,    0,

   75,    0,    0,  282,  171,  175,  181,  185,  189,  193,
  199,   97,  203,  209
};

static yyconst short int yy_def[215] =
{ 0,
  204,    1,  204,  204,  204,  204,  204,  204,  205,  206,
  206,  204,  207,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  208,  208,  208,  208,  204,  204,  204,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
  204,  204,  204,  204,  204,  204,  204,  205,  204,  205,
  209,  204,  210,  204,  204,  204,  207,  204,  207,  204,
  204,  204,  204,  204,  211,  204,  204,  204,  204,  212,
  204,  204,  204,  204,  204,  204,  208,  208,  208,  208,
  204,  208,  208,  208,  208,  208,  208,  208,  208,  208,

  208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  204,  204,  204,  213,
  210,  210,  211,  204,  204,  204,  212,  204,  204,  208,
  208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
  208,  208,  208,  213,  213,  208,  208,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  214,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
  208,  214,  214,  208,  208,  208,  208,  208,  208,  208,
  208,  208,  208,  208,  208,  208,  208,  208,  204,  208,

  208,  208,  208,    0,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204
};

static yyconst short int yy_nxt[350] =
{ 0,
    4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
   24,   25,   26,   27,   28,   29,   30,   31,   31,   31,
   31,   31,   31,   31,   32,   31,   33,   34,   31,   35,
    4,   36,   37,   31,   38,   39,   40,   41,   42,   31,
   31,   43,   31,   31,   31,   44,   45,   46,   47,   48,
   49,   31,   50,   51,   52,   53,   54,   56,   59,   61,
   61,   61,   61,   65,   62,   68,   64,   71,   73,   75,
   77,  117,   78,   78,   57,   76,   74,   72,   66,   77,
   92,   78,   78,   82,   83,   79,   85,   86,   59,  127,

   94,   93,   80,   60,   79,   95,   69,  100,   97,  101,
  102,   79,   98,   96,  110,  111,  112,   68,  113,  146,
   79,   99,  118,  103,  114,  147,  115,  203,  104,   61,
   61,  124,  124,   60,   77,  202,   78,   78,  125,  201,
  125,  124,  124,  126,  126,  126,  126,  200,   69,   79,
  126,  126,  199,  198,   79,  197,  196,  195,  194,  193,
  192,  183,  191,  190,  189,   79,  188,  187,  186,  185,
   79,   58,  184,   58,   58,   58,   58,   63,  183,   63,
   63,   67,  181,   67,   67,   67,   67,   87,  180,  179,
   87,  120,  178,  177,  120,  121,  121,  176,  121,  123,

  175,  123,  123,  123,  123,  154,  154,  174,  154,  182,
  155,  182,  182,  182,  182,  155,  173,  172,  171,  170,
  169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
  159,  158,  157,  156,  122,  122,  155,  153,  152,  151,
  150,  149,  148,  145,  144,  143,  142,  141,  140,  139,
  138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
  128,   67,  122,   58,  119,   55,  116,  109,  108,  107,
  106,  105,   91,   90,   89,   88,   84,   81,   70,   55,
  204,    3,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204
};

static yyconst short int yy_chk[350] =
{ 0,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    8,    9,   10,
   10,   11,   11,   12,   10,   13,   11,   17,   19,   21,
   22,   52,   22,   22,    8,   21,   19,   17,   12,   23,
   38,   23,   23,   26,   26,   22,   28,   28,   58,  212,

   39,   38,   22,    9,   23,   39,   13,   41,   40,   41,
   42,   22,   40,   39,   48,   48,   48,   67,   49,  109,
   23,   40,   52,   42,   49,  109,   49,  201,   42,   61,
   61,   77,   77,   58,   78,  197,   78,   78,   79,  195,
   79,  124,  124,   79,   79,  125,  125,  194,   67,   78,
  126,  126,  193,  191,  124,  190,  189,  188,  187,  185,
  184,  183,  181,  180,  178,   78,  177,  176,  173,  170,
  124,  205,  168,  205,  205,  205,  205,  206,  167,  206,
  206,  207,  166,  207,  207,  207,  207,  208,  165,  164,
  208,  209,  162,  161,  209,  210,  210,  160,  210,  211,

  157,  211,  211,  211,  211,  213,  213,  156,  213,  214,
  155,  214,  214,  214,  214,  154,  153,  152,  151,  150,
  148,  147,  146,  145,  143,  141,  139,  138,  137,  136,
  135,  134,  133,  132,  122,  121,  120,  116,  115,  113,
  112,  111,  110,  108,  106,  104,  103,  102,  101,  100,
   98,   97,   96,   95,   94,   93,   92,   90,   89,   86,
   82,   69,   63,   60,   56,   55,   50,   47,   46,   45,
   44,   43,   37,   34,   33,   32,   27,   24,   16,    5,
    3,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
  204,  204,  204,  204,  204,  204,  204,  204,  204
};

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char* yytext;
#line 1 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
#define INITIAL 0
#line 2 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
#define YYLMAX 4096

#include <stdio.h>
#include "platform/platform.h"
#include "core/stringTable.h"
#include "console/console.h"
#define _CMDGRAM_H_
#include "console/compiler.h"
#include "console/basgram.h"

using namespace Compiler;

#define YY_NEVER_INTERACTIVE 1

// Some basic parsing primitives...
static int Sc_ScanString(int ret);
static int Sc_ScanNum();
static int Sc_ScanVar();
static int Sc_ScanHex();

// Deal with debuggability of FLEX.
#ifdef TORQUE_DEBUG
#define FLEX_DEBUG 1
#else
#define FLEX_DEBUG 0
#endif

//#undef input
//#undef unput
#undef BASgetc
int BASgetc();

#define YY_INPUT(buf,result,max_size) \
{ \
   int c = '*', n; \
   for ( n = 0; n < max_size && \
           (c = BASgetc()) != EOF && c != '\n'; ++n ) \
      buf[n] = (char) c; \
   if ( c == '\n' ) \
      buf[n++] = (char) c; \
   result = n; \
}

static int lineIndex;

// Prototypes
void BASSetScanBuffer(const char* sb, const char* fn);
void BASerror(char* s, ...);

// Error reporting
void CMDerror(char* s, ...);

// Reset the parser.
void CMDrestart(FILE* in);

#line 584 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\\\BASscan.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO((void));
#else
extern int yywrap YY_PROTO((void));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO((int c, char* buf_ptr));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO((char*, yyconst char*, int));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO((void));
#else
static int input YY_PROTO((void));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int* yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

 /* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

 /* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
  * is returned in "result".
  */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

  /* No semi-colon after return; correct usage is to write "yyterminate();" -
   * we don't want an extra ';' after the "return" because that will cause
   * some compilers to complain about unreachable statements.
   */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

   /* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

 /* Code executed at the beginning of each rule, after yytext and yyleng
  * have been set up.
  */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

  /* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
{
register yy_state_type yy_current_state;
register char* yy_cp,* yy_bp;
register int yy_act;

#line 74 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"

            ;
#line 734 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\\\BASscan.cc"

    if (yy_init)
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if (!yy_start)
            yy_start = 1;	/* first start state */

        if (!yyin)
            yyin = stdin;

        if (!yyout)
            yyout = stdout;

        if (!yy_current_buffer)
            yy_current_buffer =
                yy_create_buffer(yyin, YY_BUF_SIZE);

        yy_load_buffer_state();
        }

    while (1)		/* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yy_start;
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            if (yy_accept[yy_current_state])
                {
                yy_last_accepting_state = yy_current_state;
                yy_last_accepting_cpos = yy_cp;
                }
            while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
                {
                yy_current_state = (int)yy_def[yy_current_state];
                if (yy_current_state >= 205)
                    yy_c = yy_meta[(unsigned int)yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
            ++yy_cp;
            } while (yy_base[yy_current_state] != 282);

yy_find_action:
        yy_act = yy_accept[yy_current_state];
        if (yy_act == 0)
            { /* have to back up */
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            yy_act = yy_accept[yy_current_state];
            }

        YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


        switch (yy_act)
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yy_hold_char;
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ }
    YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
;
    YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
;
    YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
;
    YY_BREAK
case 5:
YY_RULE_SETUP
#line 80 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ lineIndex++; }
    YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ return(Sc_ScanString(STRATOM)); }
    YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ return(Sc_ScanString(TAGATOM)); }
    YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opEQ);
    YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opNE);
    YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opGE);
    YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opLE);
    YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opAND);
    YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opOR);
    YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opCOLONCOLON);
    YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opMINUSMINUS);
    YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opPLUSPLUS);
    YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSTREQ);
    YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSTRNE);
    YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSHL);
    YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSHR);
    YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opPLASN);
    YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opMIASN);
    YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opMLASN);
    YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opDVASN);
    YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opMODASN);
    YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opANDASN);
    YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opXORASN);
    YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opORASN);
    YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSLASN);
    YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(BASlval.i = opSRASN);
    YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{BASlval.i = '\n'; return '@'; }
    YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{BASlval.i = '\t'; return '@'; }
    YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{BASlval.i = ' '; return '@'; }
    YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{BASlval.i = 0; return '@'; }
    YY_BREAK
case 35:
#line 111 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 36:
#line 112 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 37:
#line 113 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 38:
#line 114 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 39:
#line 115 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 40:
#line 116 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 41:
#line 117 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 42:
#line 118 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 43:
#line 119 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 44:
#line 120 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 45:
#line 121 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 46:
#line 122 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 47:
#line 123 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 48:
#line 124 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 49:
#line 125 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 50:
#line 126 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 51:
#line 127 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 52:
#line 128 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 53:
#line 129 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 54:
#line 130 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 55:
#line 131 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 56:
#line 132 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 57:
#line 133 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
case 58:
YY_RULE_SETUP
#line 133 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{       return(BASlval.i = BAStext[0]); }
    YY_BREAK
case 59:
YY_RULE_SETUP
#line 134 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwCASEOR); }
    YY_BREAK
case 60:
YY_RULE_SETUP
#line 135 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwBREAK); }
    YY_BREAK
case 61:
YY_RULE_SETUP
#line 136 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwRETURN); }
    YY_BREAK
case 62:
YY_RULE_SETUP
#line 137 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwELSE); }
    YY_BREAK
case 63:
YY_RULE_SETUP
#line 138 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwWHILE); }
    YY_BREAK
case 64:
YY_RULE_SETUP
#line 139 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwIF); }
    YY_BREAK
case 65:
YY_RULE_SETUP
#line 140 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwTHEN); }
    YY_BREAK
case 66:
YY_RULE_SETUP
#line 141 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwBEGIN); }
    YY_BREAK
case 67:
YY_RULE_SETUP
#line 142 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwBEGIN); }
    YY_BREAK
case 68:
YY_RULE_SETUP
#line 143 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwEND); }
    YY_BREAK
case 69:
YY_RULE_SETUP
#line 144 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwFOR); }
    YY_BREAK
case 70:
YY_RULE_SETUP
#line 145 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwCFOR); }
    YY_BREAK
case 71:
YY_RULE_SETUP
#line 146 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwTO); }
    YY_BREAK
case 72:
YY_RULE_SETUP
#line 147 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwSTEP); }
    YY_BREAK
case 73:
YY_RULE_SETUP
#line 148 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwCONTINUE); }
    YY_BREAK
case 74:
YY_RULE_SETUP
#line 149 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwDEFINE); }
    YY_BREAK
case 75:
YY_RULE_SETUP
#line 150 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwDEFINE); }
    YY_BREAK
case 76:
YY_RULE_SETUP
#line 151 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwDECLARE); }
    YY_BREAK
case 77:
YY_RULE_SETUP
#line 152 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwDATABLOCK); }
    YY_BREAK
case 78:
YY_RULE_SETUP
#line 153 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwCASE); }
    YY_BREAK
case 79:
YY_RULE_SETUP
#line 154 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwSWITCHSTR); }
    YY_BREAK
case 80:
YY_RULE_SETUP
#line 155 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwSWITCH); }
    YY_BREAK
case 81:
YY_RULE_SETUP
#line 156 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwDEFAULT); }
    YY_BREAK
case 82:
YY_RULE_SETUP
#line 157 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = lineIndex; return(rwPACKAGE); }
    YY_BREAK
case 83:
YY_RULE_SETUP
#line 158 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = 1; return INTCONST; }
    YY_BREAK
case 84:
YY_RULE_SETUP
#line 159 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BASlval.i = 0; return INTCONST; }
    YY_BREAK
case 85:
YY_RULE_SETUP
#line 160 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(Sc_ScanVar());
    YY_BREAK
case 86:
YY_RULE_SETUP
#line 161 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BAStext[BASleng] = 0; BASlval.s = StringTable->insert(BAStext); return(IDENT); }
    YY_BREAK
case 87:
YY_RULE_SETUP
#line 162 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(Sc_ScanHex());
    YY_BREAK
case 88:
YY_RULE_SETUP
#line 163 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
{ BAStext[BASleng] = 0; BASlval.i = atoi(BAStext); return INTCONST; }
    YY_BREAK
case 89:
YY_RULE_SETUP
#line 164 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return Sc_ScanNum();
    YY_BREAK
case 90:
YY_RULE_SETUP
#line 165 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(ILLEGAL_TOKEN);
    YY_BREAK
case 91:
YY_RULE_SETUP
#line 166 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
return(ILLEGAL_TOKEN);
    YY_BREAK
case 92:
YY_RULE_SETUP
#line 167 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"
ECHO;
    YY_BREAK
#line 1208 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\\\BASscan.cc"
case YY_STATE_EOF(INITIAL):
    yyterminate();

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int)(yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;

        if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans(yy_current_state);

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if (yy_next_state)
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch (yy_get_next_buffer())
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if (yywrap())
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if (!yy_did_buffer_switch_on_eof)
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found");
    } /* end of action switch */
        } /* end of scanning one token */
} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

    static int yy_get_next_buffer()
{
    register char* dest = yy_current_buffer->yy_ch_buf;
    register char* source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--end of buffer missed");

    if (yy_current_buffer->yy_fill_buffer == 0)
    { /* Don't try to fill the buffer, so this is an EOF. */
        if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
        {
            /* We matched a singled characater, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
        }

        else
        {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int)(yy_c_buf_p - yytext_ptr) - 1;

    for (i = 0; i < number_to_move; ++i)
        *(dest++) = *(source++);

    if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_n_chars = 0;

    else
    {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while (num_to_read <= 0)
        { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
                "input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int)(yy_c_buf_p - b->yy_ch_buf);

            if (b->yy_is_our_buffer)
            {
                int new_size = b->yy_buf_size * 2;

                if (new_size <= 0)
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char*)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc((void*)b->yy_ch_buf,
                        b->yy_buf_size + 2);
            }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if (!b->yy_ch_buf)
                YY_FATAL_ERROR(
                    "fatal error - scanner input buffer overflow");

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                number_to_move - 1;
#endif
        }

        if (num_to_read > YY_READ_BUF_SIZE)
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT((&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read);
    }

    if (yy_n_chars == 0)
    {
        if (number_to_move == YY_MORE_ADJ)
        {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart(yyin);
        }

        else
        {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
        }
    }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
{
    register yy_state_type yy_current_state;
    register char* yy_cp;

    yy_current_state = yy_start;

    for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
    {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if (yy_accept[yy_current_state])
        {
            yy_last_accepting_state = yy_current_state;
            yy_last_accepting_cpos = yy_cp;
        }
        while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
        {
            yy_current_state = (int)yy_def[yy_current_state];
            if (yy_current_state >= 205)
                yy_c = yy_meta[(unsigned int)yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
    }

    return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
#else
static yy_state_type yy_try_NUL_trans(yy_current_state)
yy_state_type yy_current_state;
#endif
{
    register int yy_is_jam;
    register char* yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if (yy_accept[yy_current_state])
    {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
    }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
        yy_current_state = (int)yy_def[yy_current_state];
        if (yy_current_state >= 205)
            yy_c = yy_meta[(unsigned int)yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int)yy_c];
    yy_is_jam = (yy_current_state == 204);

    return yy_is_jam ? 0 : yy_current_state;
}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput(int c, register char* yy_bp)
#else
static void yyunput(c, yy_bp)
int c;
register char* yy_bp;
#endif
{
    register char* yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
    { /* need to shift things up to make room */
    /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char* dest = &yy_current_buffer->yy_ch_buf[
            yy_current_buffer->yy_buf_size + 2];
        register char* source =
            &yy_current_buffer->yy_ch_buf[number_to_move];

        while (source > yy_current_buffer->yy_ch_buf)
            *--dest = *--source;

        yy_cp += (int)(dest - source);
        yy_bp += (int)(dest - source);
        yy_n_chars = yy_current_buffer->yy_buf_size;

        if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
            YY_FATAL_ERROR("flex scanner push-back overflow");
    }

    *--yy_cp = (char)c;


    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
{
    int c;

    *yy_c_buf_p = yy_hold_char;

    if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
    {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
        { /* need more input */
            yytext_ptr = yy_c_buf_p;
            ++yy_c_buf_p;

            switch (yy_get_next_buffer())
            {
            case EOB_ACT_END_OF_FILE:
            {
                if (yywrap())
                {
                    yy_c_buf_p =
                        yytext_ptr + YY_MORE_ADJ;
                    return EOF;
                }

                if (!yy_did_buffer_switch_on_eof)
                    YY_NEW_FILE;
#ifdef __cplusplus
                return yyinput();
#else
                return input();
#endif
            }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                break;

            case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
                YY_FATAL_ERROR(
                    "unexpected last match in yyinput()");
#else
                YY_FATAL_ERROR(
                    "unexpected last match in input()");
#endif
            }
        }
    }

    c = *(unsigned char*)yy_c_buf_p;	/* cast for 8-bit char's */
    *yy_c_buf_p = '\0';	/* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;


    return c;
}


#ifdef YY_USE_PROTOS
void yyrestart(FILE* input_file)
#else
void yyrestart(input_file)
FILE* input_file;
#endif
{
    if (!yy_current_buffer)
        yy_current_buffer = yy_create_buffer(yyin, YY_BUF_SIZE);

    yy_init_buffer(yy_current_buffer, input_file);
    yy_load_buffer_state();
}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
#else
void yy_switch_to_buffer(new_buffer)
YY_BUFFER_STATE new_buffer;
#endif
{
    if (yy_current_buffer == new_buffer)
        return;

    if (yy_current_buffer)
    {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state(void)
#else
void yy_load_buffer_state()
#endif
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size)
#else
YY_BUFFER_STATE yy_create_buffer(file, size)
FILE* file;
int size;
#endif
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE)yy_flex_alloc(sizeof(struct yy_buffer_state));
    if (!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char*)yy_flex_alloc(b->yy_buf_size + 2);
    if (!b->yy_ch_buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_is_our_buffer = 1;

    yy_init_buffer(b, file);

    return b;
}


#ifdef YY_USE_PROTOS
void yy_delete_buffer(YY_BUFFER_STATE b)
#else
void yy_delete_buffer(b)
YY_BUFFER_STATE b;
#endif
{
    if (!b)
        return;

    if (b == yy_current_buffer)
        yy_current_buffer = (YY_BUFFER_STATE)0;

    if (b->yy_is_our_buffer)
        yy_flex_free((void*)b->yy_ch_buf);

    yy_flex_free((void*)b);
}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO((int));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer(YY_BUFFER_STATE b, FILE* file)
#else
void yy_init_buffer(b, file)
YY_BUFFER_STATE b;
FILE* file;
#endif


{
    yy_flush_buffer(b);

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;
#endif
#endif
}


#ifdef YY_USE_PROTOS
void yy_flush_buffer(YY_BUFFER_STATE b)
#else
void yy_flush_buffer(b)
YY_BUFFER_STATE b;
#endif

{
    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if (b == yy_current_buffer)
        yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size)
#else
YY_BUFFER_STATE yy_scan_buffer(base, size)
char* base;
yy_size_t size;
#endif
{
    YY_BUFFER_STATE b;

    if (size < 2 ||
        base[size - 2] != YY_END_OF_BUFFER_CHAR ||
        base[size - 1] != YY_END_OF_BUFFER_CHAR)
        /* They forgot to leave room for the EOB's. */
        return 0;

    b = (YY_BUFFER_STATE)yy_flex_alloc(sizeof(struct yy_buffer_state));
    if (!b)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

    b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = 0;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer(b);

    return b;
}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string(yyconst char* str)
#else
YY_BUFFER_STATE yy_scan_string(str)
yyconst char* str;
#endif
{
    int len;
    for (len = 0; str[len]; ++len)
        ;

    return yy_scan_bytes(str, len);
}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes(yyconst char* bytes, int len)
#else
YY_BUFFER_STATE yy_scan_bytes(bytes, len)
yyconst char* bytes;
int len;
#endif
{
    YY_BUFFER_STATE b;
    char* buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = len + 2;
    buf = (char*)yy_flex_alloc(n);
    if (!buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

    for (i = 0; i < len; ++i)
        buf[i] = bytes[i];

    buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer(buf, n);
    if (!b)
        YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state(int new_state)
#else
static void yy_push_state(new_state)
int new_state;
#endif
{
    if (yy_start_stack_ptr >= yy_start_stack_depth)
    {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof(int);

        if (!yy_start_stack)
            yy_start_stack = (int*)yy_flex_alloc(new_size);

        else
            yy_start_stack = (int*)yy_flex_realloc(
                (void*)yy_start_stack, new_size);

        if (!yy_start_stack)
            YY_FATAL_ERROR(
                "out of memory expanding start-condition stack");
    }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
{
    if (--yy_start_stack_ptr < 0)
        YY_FATAL_ERROR("start-condition stack underflow");

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
{
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error(yyconst char msg[])
#else
static void yy_fatal_error(msg)
char msg[];
#endif
{
    (void)fprintf(stderr, "%s\n", msg);
    exit(YY_EXIT_FAILURE);
}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy(char* s1, yyconst char* s2, int n)
#else
static void yy_flex_strncpy(s1, s2, n)
char* s1;
yyconst char* s2;
int n;
#endif
{
    register int i;
    for (i = 0; i < n; ++i)
        s1[i] = s2[i];
}
#endif


#ifdef YY_USE_PROTOS
static void* yy_flex_alloc(yy_size_t size)
#else
static void* yy_flex_alloc(size)
yy_size_t size;
#endif
{
    return (void*)malloc(size);
}

#ifdef YY_USE_PROTOS
static void* yy_flex_realloc(void* ptr, yy_size_t size)
#else
static void* yy_flex_realloc(ptr, size)
void* ptr;
yy_size_t size;
#endif
{
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void*)realloc((char*)ptr, size);
}

#ifdef YY_USE_PROTOS
static void yy_flex_free(void* ptr)
#else
static void yy_flex_free(ptr)
void* ptr;
#endif
{
    free(ptr);
}

#if YY_MAIN
int main()
{
    yylex();
    return 0;
}
#endif
#line 167 "c:\\dev\\GameEngine\\torque_SVN\\trunk\\engine\\console\\BASscan.l"


/*
 * Scan character constant.
 */

 /*
  * Scan identifier.
  */

static const char* scanBuffer;
static const char* fileName;
static int scanIndex;

const char* BASGetCurrentFile()
{
    return fileName;
}

int BASGetCurrentLine()
{
    return lineIndex;
}

void BASerror(char*, ...)
{
    gSyntaxError = true;
    if (fileName)
        Con::errorf(ConsoleLogEntry::Script, "%s Line: %d - Syntax error.",
            fileName, lineIndex);
    else
        Con::errorf(ConsoleLogEntry::Script, "Syntax error in input.");
}

void BASSetScanBuffer(const char* sb, const char* fn)
{
    scanBuffer = sb;
    fileName = fn;
    scanIndex = 0;
    lineIndex = 1;
}

int BASgetc()
{
    int ret = scanBuffer[scanIndex];
    if (ret)
        scanIndex++;
    else
        ret = -1;
    return ret;
}

int BASwrap()
{
    return 1;
}

static int Sc_ScanVar()
{
    BAStext[BASleng] = 0;
    BASlval.s = StringTable->insert(BAStext);
    return(VAR);
}
/*
 * Scan string constant.
 */

 // Defined in CS_CMD.l
extern void expandEscape(char* dest, const char* src);
extern bool collapseEscape(char* buf);

static int charConv(int in)
{
    switch (in)
    {
    case 'r':
        return '\r';
    case 'n':
        return '\n';
    case 't':
        return '\t';
    default:
        return in;
    }
}

static int getHexDigit(char c)
{
    if (c >= '0' && c <= '9')
        return c - '0';
    if (c >= 'A' && c <= 'F')
        return c - 'A' + 10;
    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;
    return -1;
}

static int Sc_ScanString(int ret)
{
    BAStext[BASleng - 1] = 0;
    if (!collapseEscape(BAStext + 1))
        return -1;
    BASlval.str = (char*)consoleAlloc(dStrlen(BAStext));
    dStrcpy(BASlval.str, BAStext + 1);
    return(ret);
}


static int Sc_ScanNum()
{
    BAStext[BASleng] = 0;
    BASlval.f = atof(BAStext);
    return(FLTCONST);
}

static int Sc_ScanHex()
{
    int val = 0;
    dSscanf(BAStext, "%x", &val);
    BASlval.i = val;
    return INTCONST;
}

